# $wallpaper_path = ~/Pictures/wallpapers/arch-grey.jpg
#
# preload = $wallpaper_path
# wallpaper = , $wallpaper_path

# https://wiki.hypr.land/Hypr-Ecosystem/hyprpaper/
wallpaper{
  monitor = # eDP-1 # if  If empty, will use this wallpaper as a fallback
  path = ~/Pictures/wallpapers/mountain-night-4k.png
  fit_mode = cover # Determines how to display the image. Optional and defaults to `cover`. contain|cover|tile|fill
}
splash = false
