
$wallpaper_folder = ~/Pictures/Wallpapers/
$wallpaper_name_left = cyber-mountain-left.png
$wallpaper_name_right = cyber-mountain-right.png

# LEFT MONITOR
preload = $wallpaper_folder$wallpaper_name_left
wallpaper = DP-3, $wallpaper_folder$wallpaper_name_left

# RIGHT MONITOR
preload = $wallpaper_folder$wallpaper_name_right
wallpaper = HDMI-A-1, $wallpaper_folder$wallpaper_name_right
