
# This is an example Hyprland config file.
# Refer to the wiki for more information.
# https://wiki.hypr.land/Configuring/

# Please note not all available settings / options are set here.
# For a full list, see the wiki

# You can split this configuration into multiple files
# Create your files separately and then link them to this file like this:
# source = ~/.config/hypr/myColors.conf
source = ./conf/programs.conf
source = ./conf/autostart.conf
source = ./conf/env-vars.conf
source = ./conf/input.conf
source = ./conf/keybinds.conf
source = ./conf/look-and-feel.conf
source = ./conf/monitors.conf
source = ./conf/permissions.conf
source = ./conf/reload.conf
source = ./conf/windows-and-workspaces.conf


