################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
# 
# To list all available monitors (active and inactive):
# `hyprctl monitors all`
#
# SYNTAX:  name, resolution, position, scale 
# monitor = HDMI-A-1, 1920x10180@120, auto-left, 1
#
# monitor = eDP-1, disable

monitor = ,preferred, auto, auto
monitor = eDP-1, preferred, auto, 1
