###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

$terminal = kitty
$fileManager = thunar
$menu = wofi
$menuShow = wofi --show drun
$notificationDaemon = dunst
$networkManager = nm-applet
$wallpaperManager = hyprpaper
$statusBar = waybar
$autoMount = udiskie
$webBrowser = brave

