###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

$terminal = kitty
$fileManager = thunar
$calculator = gnome-calculator

$menu = wofi
$menuShow = wofi --show drun

$networkManager = nm-applet
$connectionEditor = nm-connection-editor

$bluetoothManager = blueman-manager
$audioManager = pavucontrol
$audioManagerClass = org.pulseaudio.pavucontrol

$wallpaperManager = hyprpaper
$statusBar = waybar

$autoMount = udiskie
$notificationDaemon = dunst

$webBrowser = brave
$webBrowserClass = brave-browser

$whatsAppWebLaunch = "brave --profile-directory=Default --app-id=hnpfjngllnobngcgfapefoaidbinmjnm"
$whatsAppWebTitle = WhatsApp Web
