##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more

# Dual Monitor Specific
workspace = 1, monitor:DP-3

# Calculator
windowrule = float, title: Calculator
windowrule = size 30% 80%, title: Calculator

# WhatsApp Web rules
windowrule = float, title: $whatsAppWebTitle 
windowrule = workspace special:magic, title: $whatsAppWebTitle
windowrule = size 80% 80%, title: $whatsAppWebTitle

# Web Browser rules
windowrule = workspace 2, class: $webBrowserClass

# $fileManager rules
windowrule = float, class: $fileManager
windowrule = size 80% 80%, class: $fileManager

# $terminal rules
windowrule = float, class: $terminal
windowrule = size 80% 80%, class: $terminal

# $bluetoothManager rules
windowrule = float, class: $bluetoothManager
windowrule = size 50% 80%, class: $bluetoothManager

# Connection Editor rules
windowrule = float, class: $connectionEditor
windowrule = size 50% 80%, class: $connectionEditor

# $audioManager rules
windowrule = float, class: $audioManagerClass
windowrule = size 50% 80%, class: $audioManagerClass

# Removes gaps when a single window is open (ignores special workspace)
# See: https://wiki.hypr.land/Configuring/Workspace-Rules/#smart-gaps
workspace = w[tv1]s[false], gapsout:0, gapsin:0
workspace = f[1]s[false], gapsout:0, gapsin:0
windowrule = bordersize 0, floating:0, onworkspace:w[tv1]s[false]
windowrule = rounding 0, floating:0, onworkspace:w[tv1]s[false]
windowrule = bordersize 0, floating:0, onworkspace:f[1]s[false]
windowrule = rounding 0, floating:0, onworkspace:f[1]s[false]

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
