##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more

# v0.53
# reloase + log https://github.com/hyprwm/Hyprland/releases/tag/v0.53.0
# config converter to v0.53 https://itsohen.github.io/hyprrulefix/

# Calculator
windowrule = float on, center on, size (monitor_w*0.3) (monitor_h*0.8), match:title Calculator

# WhatsApp Web rules
windowrule = workspace special:magic, size (monitor_w*0.8) (monitor_h*0.8), match:title $whatsAppWebTitle

# Web Browser rules
windowrule = workspace 2, match:class $webBrowserClass

# $fileManager rules
windowrule = float on, center on, size (monitor_w*0.8) (monitor_h*0.8), match:class $fileManager

# $terminal rules
windowrule = center on, size (monitor_w*0.8) (monitor_h*0.8), match:class $terminal

# $bluetoothManager rules
windowrule = float on, center on, size (monitor_w*0.5) (monitor_h*0.8), match:class $bluetoothManager

# Connection Editor rules
windowrule = float on, center on, size (monitor_w*0.5) (monitor_h*0.8), match:class $connectionEditor

# $audioManager rules
windowrule = float on, center on, size (monitor_w*0.5) (monitor_h*0.8), match:class $audioManagerClass

# Special:magic workspace rules
# workspace = special:magic, gapsout:50 100 50 100

# Removes gaps when a single window is open (ignores special workspace)
# See: https://wiki.hypr.land/Configuring/Workspace-Rules/#smart-gaps
workspace = w[tv1]s[false], gapsout:0, gapsin:0
workspace = f[1]s[false], gapsout:0, gapsin:0
windowrule = border_size 0, rounding 0, match:float 0, match:workspace w[tv1]s[false]
windowrule = border_size 0, rounding 0, match:float 0, match:workspace f[1]s[false]

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppress_event maximize, match:class .*

# Fix some dragging issues with XWayland
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0
